using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Debaters.Models;
using FluentAssertions;
using System.Collections.Generic;
using System.Linq;

namespace Debaters.Tests
{
    [TestClass]
    public class NumbertronTests
    {
        [TestMethod]
        public void NewNumberCorrectlyFiresPassingNumberInEventArguments()
        {
            var numbertron = new Numbertron();
            numbertron.MonitorEvents();
            numbertron.Generate();
            numbertron.ShouldRaise("NewNumber").WithArgs<NewNumbertronNumberArgs>(a=>a.Number is int);
        }
        [TestMethod]
        public void NumberTronCorrectlyGenerates10NonEqualNumbers()
        {
            var numbertron = new Numbertron();
            numbertron.MonitorEvents();
            List<int> results = new List<int>();
            numbertron.NewNumber += (sender, args) => results.Add(args.Number);
            for (int i = 0; i < 10; i++)
            {
                numbertron.Generate();
            }
            results.Any(i => i != results[0]).Should().Be(true, "when 10 numbers are generated by numbertron, they shouldn't be same");
        }
    }
}
